services:
  django:
    build:
      context: .
      dockerfile: dockerfile
    

  celery:
    build:
      context: .
      dockerfile: dockerfile
    command: ["celery", "-A", "base", "worker", "-l", "INFO"]
    depends_on:
      - django